version: '3'

services:

  mysql:
    build:
      context: docker/mysql
    restart: on-failure
    volumes:
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./trad_app/var/log/mysql:/var/log/mysql:consistent
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./trad_app:/app/:consistent
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: on-failure
    ports:
      - '8080:80'
    volumes:
      - ./trad_app:/app:consistent
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./trad_app/var/log/nginx:/var/log/nginx:consistent
    depends_on:
      - mysql
      - php